"""create database

Revision ID: 32f9fd037ee0
Revises: 
Create Date: 2024-08-12 03:18:28.917496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32f9fd037ee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('busket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('books_id', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('audio_books_id', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_books_id'),
    sa.UniqueConstraint('books_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_subscribe', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('artical_img', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('include_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('book_cover', sa.String(length=255), nullable=False),
    sa.Column('audio_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('Fiction', 'Adventure', 'History', 'Psychology', 'Romance', 'Fantasy', 'Mystery', 'Thriller', 'Physiognomy', 'Finance', name='category'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('include_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('book_cover', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('Fiction', 'Adventure', 'History', 'Psychology', 'Romance', 'Fantasy', 'Mystery', 'Thriller', 'Physiognomy', 'Finance', name='category'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('stripe_id', sa.String(length=20), nullable=False),
    sa.Column('book_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('audio_book')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('busket')
    # ### end Alembic commands ###
